### ISSUE TITLE
Sync issues with sub folders

### ISSUE THREAD

**Issue by achelliah** [avisi/grunt-webdav-sync#11]
Hi. Trying Grunt for the first time and need to sync folders on my local and a webdav server. single file uploads are working perfectly. When I try to sync folders and sub folders, according to webdav_sync.js (lines 178 to 197), deletes any subfolders if exists and creates a new one. I believe synchronization needs to check for folders/subfolders in the entire tree and then check for newer files. I have a big tree both on my local and the webdav server and I need to upload/overwrite only files with newer version. Is it possible to sync the folders like this ? Am I missing any configuration ? 
(Hope this is the correct forum to ask this question. Let me know if otherwise)

Thanks,
Augustine

**Comment by mitchelkuijpers** [comment]
This is a very late comment but this is fixed with the fix for #18
