### ISSUE TITLE
Grunt task fails when trying to target files only, not subfolders

### ISSUE THREAD

**Issue by spenno** [avisi/grunt-webdav-sync#18]
Hi there,

I have a folder which I'm trying to upload via grunt-webdav-sync. The folder contains a mixture of files and subfolders. I'm trying to upload *just* the files, not the subfolders. I have so far tried the following:

`local_path: 'dist/*',` and `local_path: 'dist/*.*',`

A message appears saying 'Found 5 files', but the Grunt task then fails before the uploading begins (despite the 'Start uploading files to' message appearing).

Specifying the default `local_path: 'dist/**',` (all files and subfolders) works absolutely fine.

Thanks

**Comment by mitchelkuijpers** [comment]
Hi @spenno 

I found the root cause and will cut a release in a few minutes.

**Comment by mitchelkuijpers** [comment]
Published update to `0.2.9` to try it out, please let me know if this fixed the issue :)

**Comment by spenno** [comment]
Wow, thanks for looking into this so quickly. Looks like `local_path: 'dist/*.*'` works like a treat :) Worth mentioning that `local_path: 'dist/*'` still uploads the subfolder.
